### ISSUE TITLE
[SUGGESTION] Ability to place corner stairs using shift-click modifier.

### ISSUE THREAD

**Issue by Hahahavana** [FirEmerald/DynamicVerticalSlabsAndStairs#10]
It'd be handy for fringe cases in builds, particularly ones with slabs where you want a smoother looking transition from slab into full blocks for corners, or for fancy domes. Potentially could be done by having the corner areas of the placement grid act differently on shift click, where instead of placing vertical stairs it places a corner stair block with the corner facing whichever corner of the grid was moused over.

Apologies for using Corner so many times.

**Comment by FirEmerald** [comment]
the issue is that stairs want to automatically adjust their shape to connect to other stairs. the moment the block gets updated (for instance, if you place another block next to it) it would default back to straight.

**Comment by Hahahavana** [comment]
Oh, I'm aware. I'm specifically talking about cases when you have stairs unconnected to other stair blocks, EG to round off corners or use as a transition between slabs and full blocks. A bit of a edge case, I know.

**Comment by Hahahavana** [comment]
[Example of the situation I mean. ](https://i.ibb.co/xzvRHJx/2022-09-27-19-38-25.png)

**Comment by FirEmerald** [comment]
> 

doesn't matter, the moment a block around it changes state it would revert. even if it's not a stair block.
