### ISSUE TITLE
[1.21.x] [Neoforge] Crash when generating chunks 

### ISSUE THREAD

**Issue by ffuentesm** [FirEmerald/DynamicVerticalSlabsAndStairs#102]
Crash: https://pastebin.com/nwXvQiTm
Neoforge: 21.1.77
additionalplacements-NeoForge-1.21-2.1.0.jar

From what I can see in the log, the game crashes when chunks are generated, a stone stair is created, and their coordinate crashes the game.

**Comment by FirEmerald** [comment]
Seems to be an issue with yung's extras.

**Comment by FirEmerald** [comment]
My guess is for some reason they place the block, _then_ change its state, but at that point AP connection logic has converted it to a different state for some reason, and it crashes. They should _not_ be doing it that way. They should set the state when they place the block - as in, don't "get state, set property, set block" or whatever, just set the state without getting the state first.
