### ISSUE TITLE
Crash in TerraFirmaGreg Modpack

### ISSUE THREAD

**Issue by MtgSaber** [FirEmerald/DynamicVerticalSlabsAndStairs#107]
One of my players is experiencing a consistent startup crash with this mod (v1.8.0) in the TerraFirmaGreg modpack (v0.7.14, MC 1.20.1). When he disables *just* this mod, the game starts normally. When he enables this mod, even after updating to 2.1.0, the crash happens. Here's the crash report:

[crash-2024-12-07_18.16.31-client.txt](https://github.com/user-attachments/files/18050321/crash-2024-12-07_18.16.31-client.txt)

Any help is appreciated!

**Comment by FirEmerald** [comment]
His config files must be corrupt, tell him to delete the additional placements configs and let them regenerate, and see if it still happens. If it does, have him send the config files (_just_ the additional placements ones) over.

**Comment by MtgSaber** [comment]
That fixed it. Thanks!

**Comment by MtgSaber** [comment]
Meant to close with previous comment...
