### ISSUE TITLE
[1.19.2 / BUG] DVSaS make other mods config wipe and create .bak files

### ISSUE THREAD

**Issue by murao-kun** [FirEmerald/DynamicVerticalSlabsAndStairs#11]
Due to change made in latest version of the mod ([1.19.2-1.5.0.jar](https://www.curseforge.com/minecraft/mc-mods/dynamic-vertical-slabs-and-stairs/files/4009119)) config files of other mods are wiping and creating .bak files on startup.
![image](https://user-images.githubusercontent.com/110398598/196745009-d5730388-6806-4e8c-8d1e-1bd8464a4245.png)
I made sure that my mod file is not corrupted and other mods are fine too. The issue 100% happening only with mod installed.

**Comment by Rimevel** [comment]
I think this might be the culprit. Looks like the whole config directory is targeted with "CONFIGDIR", when it should only target the config of the mod.
https://github.com/FirEmerald/DynamicVerticalSlabsAndStairs/blob/26640f4ee19a11cef90914973169029b228ae3d1/src/main/java/com/firemerald/dvsas/DVSaSMod.java#L35

**Comment by FirEmerald** [comment]
Should be fixed as of [b7fdb0170bec2c2a44566affaa04ca9e3f72e3a6](https://github.com/FirEmerald/DynamicVerticalSlabsAndStairs/commit/b7fdb0170bec2c2a44566affaa04ca9e3f72e3a6) and [d87d4883e5a967603e90069d59a4c779a2be3165](https://github.com/FirEmerald/DynamicVerticalSlabsAndStairs/commit/d87d4883e5a967603e90069d59a4c779a2be3165)
