### ISSUE TITLE
[Mod Incompatibility] with the Dynamic Ressource loading option of ModernFix

### ISSUE THREAD

**Issue by Lonseuks** [FirEmerald/DynamicVerticalSlabsAndStairs#114]
Block texture are not loaded.
I get missing texture Texture in a Block Shape when placing any slabs and stairs vertically.
The HitBoxes of the Vertically placed shape is fine tough.

**Comment by FirEmerald** [comment]
blame dynamic resource loading.

**Comment by Lonseuks** [comment]
OK yeah did went to see if the issue is from ModernFix option,
That explain it then
https://github.com/embeddedt/ModernFix/issues/503
