### ISSUE TITLE
[1.19.2 / BUG] Diagonal stair connected to upside down stair making glitch.

### ISSUE THREAD

**Issue by murao-kun** [FirEmerald/DynamicVerticalSlabsAndStairs#2]
This is how I placing stairs.
![image](https://user-images.githubusercontent.com/110398598/190922239-ef4004cf-0bf6-46a9-a874-069b8b754cd4.png)
This is what happening after.
![image](https://user-images.githubusercontent.com/110398598/190922252-50b0ada8-c614-402c-be16-7853f8a4dd06.png)

**Comment by FirEmerald** [comment]
fixed as of [6c65197faa9246535524451701af9ecce60626d3](https://github.com/FirEmerald/DynamicVerticalSlabsAndStairs/commit/6c65197faa9246535524451701af9ecce60626d3) and [7f28f4951010a5e3648eeeda3001bfd273b51575](https://github.com/FirEmerald/DynamicVerticalSlabsAndStairs/commit/7f28f4951010a5e3648eeeda3001bfd273b51575)
