### ISSUE TITLE
[1.19.2 / BUG] Placing any modded PLANK stair diagonaly replacing it with oak.

### ISSUE THREAD

**Issue by murao-kun** [FirEmerald/DynamicVerticalSlabsAndStairs#3]
This is how I placing stair.
![image](https://user-images.githubusercontent.com/110398598/190922311-64bc8002-5257-4ebf-8f0f-8eb3b71bef4a.png)
This is what happening.
![image](https://user-images.githubusercontent.com/110398598/190922320-3af16df7-e0c3-4771-a693-cd7c4e43cb21.png)

**Comment by FirEmerald** [comment]
Not sure how that is happening. Could you share what mod you are using?

**Comment by murao-kun** [comment]
Ecologics.

**Comment by FirEmerald** [comment]
fixed as of [7f58d10571edb1018bcac11a89ced7534b1bf685](https://github.com/FirEmerald/DynamicVerticalSlabsAndStairs/commit/7f58d10571edb1018bcac11a89ced7534b1bf685) and [777ef20a755b3c60b0b61190269f6624014d5a32](https://github.com/FirEmerald/DynamicVerticalSlabsAndStairs/commit/777ef20a755b3c60b0b61190269f6624014d5a32)
