### ISSUE TITLE
[1.19.2 / SUGGESTION] Add config option to disable tooltip added by mod.

### ISSUE THREAD

**Issue by murao-kun** [FirEmerald/DynamicVerticalSlabsAndStairs#4]
Add config option to disable tooltip added by mod.
![image](https://user-images.githubusercontent.com/110398598/190922361-d5aa83f3-3773-4b6c-8081-aa59557409d2.png)

**Comment by FirEmerald** [comment]
Added as of [9a837f20a9eb4c532d37fbd1df5e482dbb0c3a66](https://github.com/FirEmerald/DynamicVerticalSlabsAndStairs/commit/9a837f20a9eb4c532d37fbd1df5e482dbb0c3a66) and [27df22addb58344a3c089e924a66b28be418975e](https://github.com/FirEmerald/DynamicVerticalSlabsAndStairs/commit/27df22addb58344a3c089e924a66b28be418975e)
