### ISSUE TITLE
can't break any blocks after deleting the mod

### ISSUE THREAD

**Issue by HaterInViolet** [FirEmerald/DynamicVerticalSlabsAndStairs#47]
As the title says, every block that requires pickaxe or axe breaks as long as when using only hand. And jade shows that you can't use any tool on it. srs why is this mod so cursed >:?
![2023-11-04_10 33 30](https://github.com/FirEmerald/AdditionalPlacements/assets/149868397/faf0f71b-4b6b-4717-be05-f15074a84e47)

**Comment by HaterInViolet** [comment]
just needed to make backup and load it

**Comment by FirEmerald** [comment]
As an aside, what has happened here is that the blocks from the auto-generated tags datapack don't exist, causing tag loading to fail. simply deleting that datapack from the save's datapacks folder will fix the issue.
