### ISSUE TITLE
Crash when right clicking with an axe

### ISSUE THREAD

**Issue by Chaxis** [FirEmerald/DynamicVerticalSlabsAndStairs#48]
Right clicking with an axe on any block causes the game to crash.
I tried using Not Enough Crashes to find the issue and it seems to be an incompatibility between Additional Placements and Create, so I removed Additional Placements (I did not have this issue before installing the mod) and the game stopped crashing
I'm using Forge 47.1.3, Minecraft version 1.20.1

**Comment by FirEmerald** [comment]
I'm going to investigate the issue now but be aware you can save everyone a lot of time by including your crash report (as a file, in a spoiler, as a pastebin link, ect.) when reporting a crash - I may have been able to instantly see the issue and provide a fix without needing to wait to get to my development space.

**Comment by FirEmerald** [comment]
I can't reproduce the issue. Please provide the crashlog, or I cannot make any progress as to fixing this issue.

**Comment by Alexyssss** [comment]
[Uploading crash-2023-11-07_14.58.47-client.txt…]()

**Comment by Chaxis** [comment]
[crash-2023-11-07_14.58.47-client.txt](https://github.com/FirEmerald/AdditionalPlacements/files/13280842/crash-2023-11-07_14.58.47-client.txt)


> I can't reproduce the issue. Please provide the crashlog, or I cannot make any progress as to fixing this issue.

**Comment by FirEmerald** [comment]
Just letting you know I did look into it, and cannot reproduce it - but I did also make some changes to how the mod interfaces with the WeatheringBlock maps that may have already fixed it, and should go live in the next mod update. I'll test again before release and if I still don't have an issue I'll mark this as closed.
