### ISSUE TITLE
hotkey to disable custom placement

### ISSUE THREAD

**Issue by MrLixam** [FirEmerald/DynamicVerticalSlabsAndStairs#49]
would there be a way to add a key to disable the custom placing, to make stuff like building stairs a bit easier? perhaps there already is and I didn't see?
thanks !

**Comment by FirEmerald** [comment]
Duplicate of https://github.com/FirEmerald/AdditionalPlacements/issues/18

**Comment by FirEmerald** [comment]
Implemented as of:
Forge 1.16.5: 48baf88
Forge 1.18.2: b55dc74
Fabric 1.18.2: 9f943d3
Forge 1.19.2: 248131b
Fabric 1.19.2: 5de479f
Forge 1.19.4: cf623a5
Forge 1.20.1: e11e53a
Fabric 1.20.1: c7eb138
Forge 1.20.2: edb6c47
Fabric 1.20.2: 736f8a5

**Comment by MrLixam** [comment]
woooow thanks , really cool!
