### ISSUE TITLE
[SUGGESTION] Compatibility / Integration with Double Slabs Mod. (SORRY)

### ISSUE THREAD

**Issue by VOLKOUL** [FirEmerald/DynamicVerticalSlabsAndStairs#50]
I know that such thing has been requested before. **Twice.** I apologize for bringing this up again, but I might have a _somewhat_ achievable workaround. In https://github.com/FirEmerald/AdditionalPlacements/issues/26 you state that:

"The problem arises in how Double Slabs handles the block placement code - it assumes (normally correctly so) that the placed block is the normal block for the item, whereas this mod changes the block placed when placing vertically." 

Sooo, I suggest adopting the Double Slabs method of handling stuff, basically deleting the current code **responsible for slabs only** and replacing it, thus making this mod a fork of Double Slabs, BUT BETTEEER! I know, sounds radical, but that way players will get exactly what they want: double slabs and vertical double slabs, stairs, carpets, pressure plates, wall and ceiling placement, KleeSab like behaviour and visual placement indicators! I myself am not a modder and don't know anything about code, but I think (just think) that it's not as difficult as it sounds. I hope you'll consider this :D

**Comment by FirEmerald** [comment]
I think you misunderstand: Doubleslabs does *not* replace any code. Nor is that the issue at hand here - the issue is that doubleslabs doesn't actually check that a slab's placed blockstate is the same block as the slab item's block.
