### ISSUE TITLE
Bug: Texture missing when vertical slab moved by piston

### ISSUE THREAD

**Issue by stlouisn** [FirEmerald/DynamicVerticalSlabsAndStairs#52]
vertically placed slab's texture is momentarily missing as block is being moved by a piston.

![1](https://github.com/FirEmerald/AdditionalPlacements/assets/26663606/3324ac27-2cae-4a84-ad4f-e12244a0ad40)

![2](https://github.com/FirEmerald/AdditionalPlacements/assets/26663606/26865edc-d79f-408f-afb9-bcd874b2156c)

![3](https://github.com/FirEmerald/AdditionalPlacements/assets/26663606/8971f45c-7148-4cff-b9c2-94b98f26d0b4)

**Comment by FirEmerald** [comment]
should be fixed in 2.0.0+
