### ISSUE TITLE
Mod crashes server

### ISSUE THREAD

**Issue by dahcat1** [FirEmerald/DynamicVerticalSlabsAndStairs#56]
When i add the mod to my server, the server loads for a bit but then crashes
![one](https://github.com/FirEmerald/AdditionalPlacements/assets/67819275/92e7a29b-d296-4ea4-b899-71d4efda4696)
![two](https://github.com/FirEmerald/AdditionalPlacements/assets/67819275/7e31d510-af09-4107-9ba1-a51c74ea7ff1)

**Comment by FirEmerald** [comment]
Could you put the actual server log please? and not just some screenshots of the console?

**Comment by dahcat1** [comment]
[latest.log](https://github.com/FirEmerald/AdditionalPlacements/files/13760707/latest.log)

**Comment by FirEmerald** [comment]
make sure it's the latest log?

**Comment by dahcat1** [comment]
it is from about 2-3 minutes ago

**Comment by FirEmerald** [comment]
It doesn't have a crash or even make mention of the additional placements mod.

**Comment by dahcat1** [comment]
the only other log i have is from a day ago, let me try to start it again to see if it generates a log

**Comment by dahcat1** [comment]
[2023-12-21-2.log](https://github.com/FirEmerald/AdditionalPlacements/files/13760719/2023-12-21-2.log)
found it, my bad for the inconvenience

**Comment by FirEmerald** [comment]
no crash there either. try crashlogs instead.

**Comment by dahcat1** [comment]
It doesnt seem to generate a crash report, let me try a few thing to see if i can get one to appear

**Comment by dahcat1** [comment]
I cant get one to appear, i'll try to go ask on the host discord

**Comment by FirEmerald** [comment]
If this is on 1.16.5 it _might_ be fixed as of Implemented as of 48baf88 but I can't say for certain

**Comment by FirEmerald** [comment]
I'm going to go ahead and close this issue as it's not had any activity.
