### ISSUE TITLE
[SUGGESTION] Mod compatibility with Quark and Mekanism

### ISSUE THREAD

**Issue by Bazyliii** [FirEmerald/DynamicVerticalSlabsAndStairs#6]
If possible can you add compatibility for Mekanism additions and Quark slabs and stairs?

**Comment by FirEmerald** [comment]
Assuming those mods are using the vanilla SlabBlock and StairBlock there shouldn't be any compat _to_ make.

**Comment by FirEmerald** [comment]
Well heck I forgot to update the 1.19 mod to not reject slabs with extra blockstate properties, will fix

**Comment by FirEmerald** [comment]
Alright, Mekanism is fixed with [ba45bdbe3bfbd39d1725af794c62826e1d19b96d](https://github.com/FirEmerald/DynamicVerticalSlabsAndStairs/commit/ba45bdbe3bfbd39d1725af794c62826e1d19b96d), quark doesn't work because they do some really weird and quite frankly **WRONG** registration work and I'm not going to attempt to make it work manually. That's on them, go open an issue in their github instead.

**Comment by Bazyliii** [comment]
Ok, sadly newest version of Create isn't working too can you take a look in that? Thx!

**Comment by FirEmerald** [comment]
I have identified the issue - mod events don't respect the event priority outside of the mod's own events, so even though the priority for the block registration event is LOWEST, it still runs before the NORMAL priority registration events of mods loaded after it.

**Comment by FirEmerald** [comment]
fixed as of [93b47f99f6076ae1d3571fefac37be7e1e926993](https://github.com/FirEmerald/DynamicVerticalSlabsAndStairs/commit/93b47f99f6076ae1d3571fefac37be7e1e926993) and [26640f4ee19a11cef90914973169029b228ae3d1](https://github.com/FirEmerald/DynamicVerticalSlabsAndStairs/commit/26640f4ee19a11cef90914973169029b228ae3d1)

**Comment by Bazyliii** [comment]
I have found another bug with Mekanism compatibility. Transparent plastic's slabs and stairs when placed are just plain white, without any transparency. There maybe more incompatibilities with other mods that add transparent slabs and stairs. But I could't test it.

![2022-09-29_16 33 33](https://user-images.githubusercontent.com/67436562/193303978-2522bf5c-3db2-4352-a347-37e1fea4e140.png)

**Comment by FirEmerald** [comment]
Most likely they aren't being properly set to the correct render types, I'll have to see what I did wrong there

**Comment by FirEmerald** [comment]
Is this in 1.18.2 or 1.19.2? it's important to know as 1.19.2 actually gets the render layer by the model.

**Comment by Bazyliii** [comment]
All bugs that I post are in 1.19.2 and always in newest version of mods :)

**Comment by FirEmerald** [comment]
Fixed as of [d5d82a3424f64e35caf4b4b2d5552a110dad7442](https://github.com/FirEmerald/DynamicVerticalSlabsAndStairs/commit/d5d82a3424f64e35caf4b4b2d5552a110dad7442) and
[b9279289733a8874289ccbd51f5770fe94164fb9](https://github.com/FirEmerald/DynamicVerticalSlabsAndStairs/commit/b9279289733a8874289ccbd51f5770fe94164fb9)
