### ISSUE TITLE
[suggestion] Config option to disable mod on client

### ISSUE THREAD

**Issue by JV63177** [FirEmerald/DynamicVerticalSlabsAndStairs#63]
Hello 

I have a server running with your mod but some players dont want to use it so i wanted to know if its possible to add a config option for the client to disable the custom placement rules.

**Comment by FirEmerald** [comment]
This would require some form of networking to work; and as such is better suited to just be a toggle keybind which I am working on adding now.

**Comment by JV63177** [comment]
To be honest that sounds like a much better idea lol. I thought of it as well when creating the issue but I didn't really think it would be easier then a client config option or smt lol.

**Comment by FirEmerald** [comment]
Keybind has been implemented as of:
Forge 1.16.5: 48baf88
Forge 1.18.2: b55dc74
Fabric 1.18.2: 9f943d3
Forge 1.19.2: 248131b
Fabric 1.19.2: 5de479f
Forge 1.19.4: cf623a5
Forge 1.20.1: e11e53a
Fabric 1.20.1: c7eb138
Forge 1.20.2: edb6c47
Fabric 1.20.2: 736f8a5
