### ISSUE TITLE
Crash when reloading resources

### ISSUE THREAD

**Issue by Manos-of-Fate** [FirEmerald/DynamicVerticalSlabsAndStairs#64]
Reloading resources (either by changing the active resource packs or F3+T) crashes the game every time. Tested with only this mod and its dependencies active.

---- Minecraft Crash Report ----
// Sorry :(

Time: 2024-02-12 10:23:11
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_3302.method_25931(net.minecraft.class_3302$class_4045, net.minecraft.class_3300, net.minecraft.class_3695, net.minecraft.class_3695, java.util.concurrent.Executor, java.util.concurrent.Executor)" because "$$3" is null
	at net.minecraft.class_4014.method_18368(class_4014.java:32)
	at net.minecraft.class_4014.<init>(class_4014.java:44)
	at net.minecraft.class_4014.method_18369(class_4014.java:32)
	at net.minecraft.class_4014.method_40087(class_4014.java:101)
	at net.minecraft.class_3304.method_18232(class_3304.java:47)
	at net.minecraft.class_310.method_36561(class_310.java:950)
	at net.minecraft.class_310.method_1521(class_310.java:928)
	at net.minecraft.class_309.method_1468(class_309.java:225)
	at net.minecraft.class_309.method_1466(class_309.java:432)
	at net.minecraft.class_309.method_22678(class_309.java:477)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_309.method_22676(class_309.java:477)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:212)
	at net.minecraft.class_1041.method_15998(class_1041.java:288)
	at net.minecraft.class_310.method_1523(class_310.java:1241)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_4014.method_18368(class_4014.java:32)
	at net.minecraft.class_4014.<init>(class_4014.java:44)
	at net.minecraft.class_4014.method_18369(class_4014.java:32)
	at net.minecraft.class_4014.method_40087(class_4014.java:101)
	at net.minecraft.class_3304.method_18232(class_3304.java:47)
	at net.minecraft.class_310.method_36561(class_310.java:950)
	at net.minecraft.class_310.method_1521(class_310.java:928)
	at net.minecraft.class_309.method_1468(class_309.java:225)
	at net.minecraft.class_309.method_1466(class_309.java:432)
	at net.minecraft.class_309.method_22678(class_309.java:477)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_309.method_22676(class_309.java:477)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:212)

-- Affected level --
Details:
	All players: 1 total; [class_746['Manos_of_Fate'/1, l='ClientLevel', x=7.50, y=-60.00, z=-9.50]]
	Chunk stats: 5041, 3653
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,-60,0), Section: (at 0,4,0 in 0,-4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 2029 game time, 2029 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:826)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- Last reload --
Details:
	Reload number: 2
	Reload reason: manual
	Finished: No
	Packs: Additional Placements blockstate redirection pack, vanilla, fabric, file/Yourscraft

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Mac OS X (x86_64) version 13.6.3
	Java Version: 17.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1330877600 bytes (1269 MiB) / 2466250752 bytes (2352 MiB) up to 8455716864 bytes (8064 MiB)
	CPUs: 6
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 13
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 6
	Graphics card #0 name: Radeon Pro 580X
	Graphics card #0 vendor: AMD (0x1002)
	Graphics card #0 VRAM (MB): 8192.00
	Graphics card #0 deviceId: 0x67df
	Graphics card #0 versionInfo: Revision ID: 0x00c0, ROM Revision: 113-D0008A-042, VBIOS Version: 113-D0008A1X-009, EFI Driver Version: 01.B1.042, Adapter Firmware Version:  3.0a
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 0.00
	Memory slot #1 clockSpeed (GHz): -0.00
	Memory slot #1 type: Empty
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 2.67
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 0.00
	Memory slot #3 clockSpeed (GHz): -0.00
	Memory slot #3 type: Empty
	Virtual memory max (MB): 31744.00
	Virtual memory used (MB): 24828.64
	Swap memory total (MB): 15360.00
	Swap memory used (MB): 13728.50
	JVM Flags: 2 total; -Xms1024m -Xmx8064m
	Fabric Mods: 
		additionalplacements: Additional Placements 1.7.6
		fabric-api: Fabric API 0.91.0+1.20.1
			fabric-api-base: Fabric API Base 0.4.30+7abfd51577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.12+215bbe9677
			fabric-block-api-v1: Fabric Block API (v1) 1.0.10+92a0d36777
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.0+92a0d36777
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.40+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.1+97bb207577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.63+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.10+57aed33f77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.3+d7b148e077
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.53+8536527b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.39+ae9f657a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.11+d7b148e077
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.0+96dfa95977
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.44+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.8+d7b148e077
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.2+709a987177
			fabric-models-v0: Fabric Models (v0) 0.4.1+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.10+eeb8eb3677
			fabric-networking-v0: Fabric Networking (v0) 0.3.50+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.2+4ee0bc6077
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.20+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.2+4df89eb277
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.0+39a511ba77
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.0+39a511ba77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.45+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.36+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.48+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.7+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.7+29de845d77
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.7+b3afc78b77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.29+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.3+c81d263177
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabricloader: Fabric Loader 0.15.6
			mixinextras: MixinExtras 0.3.2
		forgeconfigapiport: Forge Config API Port 8.0.0
		java: Java HotSpot(TM) 64-Bit Server VM 17
		minecraft: Minecraft 1.20.1
		porting_lib: Porting Lib 2.1.1168+1.20.1
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
			mm: Manningham Mills 2.3
			porting_lib_accessors: Porting Lib Accessors 2.1.1168+1.20.1
			porting_lib_asm: Porting Lib ASM 2.1.1168+1.20.1
			porting_lib_attributes: Porting Lib Attributes 2.1.1168+1.20.1
			porting_lib_base: Porting Lib Base 2.1.1168+1.20.1
			porting_lib_brewing: Porting Lib Brewing 2.1.1168+1.20.1
			porting_lib_chunk_loading: Porting Lib Chunk Loading 2.1.1168+1.20.1
			porting_lib_client_events: Porting Lib Client Events 2.1.1168+1.20.1
			porting_lib_common: Porting Lib Common 2.1.1168+1.20.1
			porting_lib_config: Porting Lib Config 2.1.1168+1.20.1
			porting_lib_core: Porting Lib Core 2.1.1168+1.20.1
			porting_lib_data: Porting Lib Data 2.1.1168+1.20.1
			porting_lib_entity: Porting Lib Entity 2.1.1168+1.20.1
			porting_lib_extensions: Porting Lib Extensions 2.1.1168+1.20.1
			porting_lib_fluids: Porting Lib Fluids 2.1.1168+1.20.1
			porting_lib_gametest: Porting Lib GameTest 2.1.1168+1.20.1
			porting_lib_items: Porting Lib Items 2.1.1168+1.20.1
			porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.1168+1.20.1
			porting_lib_loot: Porting Lib Loot 2.1.1168+1.20.1
			porting_lib_mixin_extensions: Porting Lib Mixin Extensions 2.1.1168+1.20.1
			porting_lib_model_builders: Porting Lib Model Builders 2.1.1168+1.20.1
			porting_lib_model_generators: Porting Lib Model Generators 2.1.1168+1.20.1
			porting_lib_model_loader: Porting Lib Model Loader 2.1.1168+1.20.1
			porting_lib_model_materials: Porting Lib Model Materials 2.1.1168+1.20.1
			porting_lib_models: Porting Lib Models 2.1.1168+1.20.1
			porting_lib_networking: Porting Lib Networking 2.1.1168+1.20.1
			porting_lib_obj_loader: Porting Lib Obj Loader 2.1.1168+1.20.1
			porting_lib_recipe_book_categories: Porting Lib Recipe Book Categories 2.1.1168+1.20.1
			porting_lib_registries: Porting Lib Registries 2.1.1168+1.20.1
			porting_lib_tags: Porting Lib Tags 3.0
			porting_lib_tool_actions: Porting Lib Tool Actions 2.1.1168+1.20.1
			porting_lib_transfer: Porting Lib Transfer 2.1.1168+1.20.1
			porting_lib_utility: Porting Lib Utility 2.1.1168+1.20.1
			reach-entity-attributes: Reach Entity Attributes 2.4.0
	Launched Version: 1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: AMD Radeon Pro 580X OpenGL Engine GL version 4.1 ATI-4.14.1, ATI Technologies Inc.
	Window size: 5120x2880
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, fabric, file/Yourscraft (incompatible)
	Current Language: en_us
	CPU: 6x Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['Manos_of_Fate'/1, l='ServerLevel[Crash Test]', x=7.50, y=-60.00, z=-9.50]]
	Data Packs: Additional Placements blockstate redirection pack (incompatible), vanilla, fabric, file/additional_placements_generated_tags (incompatible)
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
#@!@# Game crashed! Crash report saved to: #@!@# /Users/Manos/Library/Application Support/PrismLauncher/instances/1.20.1 Deco Fabric/.minecraft/crash-reports/crash-2024-02-12_10.23.11-client.txt
Process exited with code 255.

**Comment by FirEmerald** [comment]
I cannot reproduce this crash. Have you tried disabling other mods to see if it's an issue with one of them? tell me which one if you do find out.

**Comment by Manos-of-Fate** [comment]
I think I solved the mystery. PortingLib's wonky versioning confused Prism, causing it to think the 1.19.2 version was for 1.20.1 instead. When I forced it to download the correct version it stopped happening. I have no idea why that was *only* crashing when reloading resources with your mod active, but I don't think you need to worry about it lol.
