### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Gamemassa** [FirEmerald/DynamicVerticalSlabsAndStairs#67]
Not sure if this is an issue with Additional Placements or Porting Lib, but I'm using the latest versions of both (latest for Porting Lib just got released this morning) with Fabric 1.20.4 and I got this latest.log

https://gist.github.com/Gamemassa/63189c21f74ee11c96dcd57b24e9b919

**Comment by FirEmerald** [comment]
Certified bruh moment. Just use 1.20.1 as required by the mod.
`A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Porting Lib Models' (porting_lib_models) 2.2.1-beta+1.20.1 with any version that is compatible with:
		 - minecraft 1.20.4
	 - Replace mod 'Porting Lib Model Generators' (porting_lib_model_generators) 2.2.1-beta+1.20.1 with any version that is compatible with:
		 - minecraft 1.20.4
	 - Replace mod 'Porting Lib Model Loader' (porting_lib_model_loader) 2.2.1-beta+1.20.1 with any version that is compatible with:
		 - minecraft 1.20.4`

**Comment by Gamemassa** [comment]
> Certified bruh moment. Just use 1.20.1 as required by the mod. `A potential solution has been determined, this may resolve your problem: - Replace mod 'Porting Lib Models' (porting_lib_models) 2.2.1-beta+1.20.1 with any version that is compatible with: - minecraft 1.20.4 - Replace mod 'Porting Lib Model Generators' (porting_lib_model_generators) 2.2.1-beta+1.20.1 with any version that is compatible with: - minecraft 1.20.4 - Replace mod 'Porting Lib Model Loader' (porting_lib_model_loader) 2.2.1-beta+1.20.1 with any version that is compatible with: - minecraft 1.20.4`

Is there a 1.20.4 update of Additional Placements planned for a future release?

**Comment by FirEmerald** [comment]
Any versions of Additional Placements running on Fabric will depend on having a working version of PortingLib for that version.

**Comment by Gamemassa** [comment]
> Any versions of Additional Placements running on Fabric will depend on having a working version of PortingLib for that version.

Yeah, Porting Lib just got updated for 1.20.4 this morning, is why I asked. And no rush. I don't care how soon it comes, I would just like to know if it's coming at all.

**Comment by FirEmerald** [comment]
I got in contact with the team and the 1.20.2-1.20.4 versions aren't actually real, they're all just the 1.20.1 version that was mistakenly marked as those versions.
So, no, it's not really "in the works" yet as there's not actually a 1.20.4 version of Porting Lib.

**Comment by Gamemassa** [comment]
I actually told them that the first three Alpha versions they uploaded were incorrectly marked (other users may have told them as well). But the two Beta versions uploaded after that appear to be working with 1.20.4, or at least they haven't caused any issues in my custom modpack yet.

**Comment by FirEmerald** [comment]
I'm not sure which versions you mean, if you are referring to 2.2.0 and 2.2.1 I can't use those as they specifically require minecraft 1.20.1. Trying to use them in a 1.20.4 development workspace just pops up a dependency issue.

**Comment by FirEmerald** [comment]
`Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Porting Lib Models' (porting_lib_models) 2.2.1-beta+1.20.1 with any version that is compatible with:
		 - minecraft 1.20.4
	 - Replace mod 'Porting Lib Model Generators' (porting_lib_model_generators) 2.2.1-beta+1.20.1 with any version that is compatible with:
		 - minecraft 1.20.4
	 - Replace mod 'Porting Lib Model Loader' (porting_lib_model_loader) 2.2.1-beta+1.20.1 with any version that is compatible with:
		 - minecraft 1.20.4
More details:
	 - Mod 'Porting Lib Models' (porting_lib_models) 2.2.1-beta+1.20.1 requires version 1.20.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.4!
	 - Mod 'Porting Lib Model Loader' (porting_lib_model_loader) 2.2.1-beta+1.20.1 requires version 1.20.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.4!
	 - Mod 'Porting Lib Model Generators' (porting_lib_model_generators) 2.2.1-beta+1.20.1 requires version 1.20.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.4!
	 - Mod 'Porting Lib Accessors' (porting_lib_accessors) 2.2.1-beta+1.20.1 requires version 1.20.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.4!
	 - Mod 'Porting Lib ASM' (porting_lib_asm) 2.2.1-beta+1.20.1 requires version 1.20.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.4!
	 - Mod 'Porting Lib Attributes' (porting_lib_attributes) 2.2.1-beta+1.20.1 requires version 1.20.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.4!
	 - Mod 'Porting Lib Base' (porting_lib_base) 2.2.1-beta+1.20.1 requires version 1.20.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.4!
	 - Mod 'Porting Lib Brewing' (porting_lib_brewing) 2.2.1-beta+1.20.1 requires version 1.20.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.4!
	 - Mod 'Porting Lib Chunk Loading' (porting_lib_chunk_loading) 2.2.1-beta+1.20.1 requires version 1.20.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.4!
	 - Mod 'Porting Lib Client Events' (porting_lib_client_events) 2.2.1-beta+1.20.1 requires version 1.20.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.4!
	 - Mod 'Porting Lib Common' (porting_lib_common) 2.2.1-beta+1.20.1 requires version 1.20.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.4!
	 - Mod 'Porting Lib Config' (porting_lib_config) 2.2.1-beta+1.20.1 requires version 1.20.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.4!
	 - Mod 'Porting Lib Core' (porting_lib_core) 2.2.1-beta+1.20.1 requires version 1.20.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.4!
	 - Mod 'Porting Lib Data' (porting_lib_data) 2.2.1-beta+1.20.1 requires version 1.20.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.4!
	 - Mod 'Porting Lib Entity' (porting_lib_entity) 2.2.1-beta+1.20.1 requires version 1.20.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.4!
	 - Mod 'Porting Lib Extensions' (porting_lib_extensions) 2.2.1-beta+1.20.1 requires version 1.20.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.4!
	 - Mod 'Porting Lib Fluids' (porting_lib_fluids) 2.2.1-beta+1.20.1 requires version 1.20.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.4!
	 - Mod 'Porting Lib GameTest' (porting_lib_gametest) 2.2.1-beta+1.20.1 requires version 1.20.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.4!
	 - Mod 'Porting Lib Items' (porting_lib_items) 2.2.1-beta+1.20.1 requires version 1.20.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.4!
	 - Mod 'Porting Lib Lazy Register' (porting_lib_lazy_registration) 2.2.1-beta+1.20.1 requires version 1.20.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.4!
	 - Mod 'Porting Lib Loot' (porting_lib_loot) 2.2.1-beta+1.20.1 requires version 1.20.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.4!
	 - Mod 'Porting Lib Mixin Extensions' (porting_lib_mixin_extensions) 2.2.1-beta+1.20.1 requires version 1.20.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.4!
	 - Mod 'Porting Lib Model Builders' (porting_lib_model_builders) 2.2.1-beta+1.20.1 requires version 1.20.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.4!
	 - Mod 'Porting Lib Model Materials' (porting_lib_model_materials) 2.2.1-beta+1.20.1 requires version 1.20.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.4!
	 - Mod 'Porting Lib Networking' (porting_lib_networking) 2.2.1-beta+1.20.1 requires version 1.20.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.4!
	 - Mod 'Porting Lib Obj Loader' (porting_lib_obj_loader) 2.2.1-beta+1.20.1 requires version 1.20.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.4!
	 - Mod 'Porting Lib Recipe Book Categories' (porting_lib_recipe_book_categories) 2.2.1-beta+1.20.1 requires version 1.20.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.4!
	 - Mod 'Porting Lib Registries' (porting_lib_registries) 2.2.1-beta+1.20.1 requires version 1.20.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.4!
	 - Mod 'Porting Lib Tags' (porting_lib_tags) 3.0 requires version 1.20.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.4!
	 - Mod 'Porting Lib Tool Actions' (porting_lib_tool_actions) 2.2.1-beta+1.20.1 requires version 1.20.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.4!
	 - Mod 'Porting Lib Transfer' (porting_lib_transfer) 2.2.1-beta+1.20.1 requires version 1.20.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.4!
	 - Mod 'Porting Lib Utility' (porting_lib_utility) 2.2.1-beta+1.20.1 requires version 1.20.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.4!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
	at org.polymc.EntryPoint.listen(EntryPoint.java:144)
	at org.polymc.EntryPoint.main(EntryPoint.java:74)
`
Here's what happens if I build a 1.20.4 version anyways and run it using the latest version of portinglib

**Comment by Gamemassa** [comment]
> I'm not sure which versions you mean, if you are referring to 2.2.0 and 2.2.1 I can't use those as they specifically require minecraft 1.20.1. Trying to use them in a 1.20.4 development workspace just pops up a dependency issue.

Sorry, I meant that Porting Lib versions 2.2.0 and 2.2.1 both appear to be working on Fabric 1.20.4, but I didn't actually try them with Additional Placements yet. Or at least, those versions are not causing a crash on startup or world load in 1.20.4

**Comment by FirEmerald** [comment]
Referring back to what I said before, 2.2.0 and 2.2.1 both will not load in 1.20.4. I'm not sure why you can still launch it but if I try to use them in both the MDK and in regular modded MC I get a dependency error.
Regardless, I do have what _should_ be a working 1.20.4 fabric version that is only waiting for a working 1.20.4 release of porting lib.
