### ISSUE TITLE
Crash on World Load with both Additional Placements and Supplementaries installed

### ISSUE THREAD

**Issue by AlexTheSuprWolf** [FirEmerald/DynamicVerticalSlabsAndStairs#68]
with both installed, the game will crash shortly after loading into a world.

[crash-2024-02-28_23.53.51-server.txt](https://github.com/FirEmerald/AdditionalPlacements/files/14443034/crash-2024-02-28_23.53.51-server.txt)

**Comment by FirEmerald** [comment]
Looking at the crash log, it seems most likely to be an issue on either Supplementaries' end or Porting Lib. Try sending the crashlog over to Supplemenataries and see what they say.

**Comment by AlexTheSuprWolf** [comment]
upon further testing, i've found the crash is between supplementaries and porting lib, with no connection to additional placements.

**Comment by FirEmerald** [comment]
> upon further testing, i've found the crash is between supplementaries and porting lib, with no connection to additional placements.

did you report it to them?

**Comment by AlexTheSuprWolf** [comment]
just made a bug report to porting lib
