### ISSUE TITLE
On server blocks revert to vanilla placements

### ISSUE THREAD

**Issue by WinterEcho** [FirEmerald/DynamicVerticalSlabsAndStairs#69]
Running this on my own modpack, and the block placement works correctly in singleplayer but for the server the placement auto-reverts to a vanilla placement.

For example, placing a slab against a wall so it is vertical has the slab appear as it should for a moment before swapping to either a vanilla top or bottom slab.

**Comment by FirEmerald** [comment]
Sounds like on the server end the placement logic isn't running (blocks are placed on client first, then the server notifies the client of a blockstate change so if the placement logic is different between the two it's going to appear like it switches after a delay)

Please note what game version and mod loader you are using, and list any mods on the server and the client (separate lists please!)

**Comment by WinterEcho** [comment]
Running on 1.20.1 using Fabric 0.15.7

Mod list for server:
[Server Mod List.txt](https://github.com/FirEmerald/AdditionalPlacements/files/14477595/Server.Mod.List.txt)

Mod list for client:
[Client Mod List.txt](https://github.com/FirEmerald/AdditionalPlacements/files/14477596/Client.Mod.List.txt)

**Comment by WinterEcho** [comment]
Okay, just restarted the server and it seems fixed now. Strange that it didn't change when the server restarted earlier though...
Anyway, it seems to be fixed, might have just needed a couple restarts for some reason. Thanks anyway!!
