### ISSUE TITLE
[1.19.4][Bug] 32x texture packs do not properly render vertical slabs, the texture wraps

### ISSUE THREAD

**Issue by Kogitsune** [FirEmerald/DynamicVerticalSlabsAndStairs#70]
![2024-03-10_17 48 06](https://github.com/FirEmerald/AdditionalPlacements/assets/5000863/8cf7294e-0db3-465f-92b5-b3a848e14648)

Left to right:

Cobble stone block, cobble stone slab (standard placement), cobble stone slab placed vertically.

16x texture packs, such as the default textures, work perfectly fine. Texture pack in use is [Alacrity](https://www.curseforge.com/minecraft/texture-packs/alacrity).

**Comment by FirEmerald** [comment]
This is an issue with the resourcepack in question. It's modifying the slab models to use half the normal texture size, which leads to this issue as the block is using the full texture. I don't see any easy fix for this. The resourcepack SHOULD have put the different section of textures as different sprites instead.
