### ISSUE TITLE
Log spam for exporting tags and reloading including mods that are no longer present or even relevant

### ISSUE THREAD

**Issue by Barerock** [FirEmerald/DynamicVerticalSlabsAndStairs#74]
[latest.log](https://github.com/FirEmerald/AdditionalPlacements/files/14817243/latest.log)
I no longer have Vanilla Refresh and that mod does not add any blocks at all. I keep getting this spam and I'm at my wit's end because it seems totally disconnected from any real cause, it'll just show up randomly.

**Comment by Barerock** [comment]
The Placeables mod doesn't have a community or issues forum to troubleshoot, so here I am for at least this mod and I've asked in VR's discord.

**Comment by Barerock** [comment]
Something I've noticed is that this log spam happens when I don't get the message that AP logic is enabled, meaning it's unable to load. Either causing the issue or just being affected by it. I'm not sure. After an embeddium chunk loading crash the log is no longer be spammed. IDK

**Comment by Barerock** [comment]
Eehh it's probably because i removed a mod that adds tags. It is weird that AP reads mods that aren't active anymore though.

**Comment by FirEmerald** [comment]
This log spam is entirely unrelated to Additional Placements. You have loot tables in a mod or datapack that reference missing blocks.
