### ISSUE TITLE
Mod compatibility

### ISSUE THREAD

**Issue by PCSpinner** [FirEmerald/DynamicVerticalSlabsAndStairs#78]
Minecraft 1.20.1
Forge: 47.2.0
Additional Placements: 1.8.0
Additional Blocks Stone Edition: 2.1.3

I'm having no problem with Placements registering stairs and slabs from minecraft, quark, stoneworks, twigs... but it won't grab the stairs and slabs from "Additional Blocks: Stone Edition." 

I have tried using CraftTweaker to add the stairs to <tag:blocks:minecraft:stairs> with no results.

Is there something I'm missing?

**Comment by FirEmerald** [comment]
If those stairs and slabs don't use the vanilla classes, the mod can't detect them. My guess is that's what's going on.
EDIT to specify: subclasses of the vanilla slab/stair classes work. Same for carpets and pressure plates.

**Comment by FirEmerald** [comment]
Yep, checked their source. Custom classes. Would need a special handler.

**Comment by benjaminaragon** [comment]
Are you working on support for blocks that don't use the vanilla classes?

**Comment by ali-afk** [comment]
I would like to add that this is the same situation for Create: Connected's copycat stairs. They can be placed in different direction as normal, but once you start rotating or flipping them the game crashes.
