### ISSUE TITLE
All particles for vertical single slabs are using (birch?) wood particles.

### ISSUE THREAD

**Issue by smr1618** [FirEmerald/DynamicVerticalSlabsAndStairs#79]
When breaking vertical single slabs, all block types are emitting birch (I think, unsure) particles.
![Untitled video - Made with Clipchamp](https://github.com/FirEmerald/AdditionalPlacements/assets/144867620/6a4f1c34-76c5-4804-98d6-c427f84ad252)

**Comment by FirEmerald** [comment]
Should be fixed now. Give it a test, see if it still happens.
