### ISSUE TITLE
Glass Slabs

### ISSUE THREAD

**Issue by WHiZSTA** [FirEmerald/DynamicVerticalSlabsAndStairs#84]
I've tried 3 different mods that add glass slabs, and they all have this issue. Seeing glass is  different than regular blocks by being transparent rather than opaque the glitch really looks bad.

Basically what i'm asking for is when creating the vertical slab type, on anything with *glass* in the name specifically(but could apply to others too such as the smooth stone slab), to see if you can invert/swap the top and side textures assigned. Otherwise what happens is the small side texture is used for a full vertical slab creating this mess.

![2024-06-27_20 49 38](https://github.com/FirEmerald/AdditionalPlacements/assets/18521070/9f8855ea-5e9e-495b-b24f-ed0c0a5acf66)

**Comment by FirEmerald** [comment]
should be fixed in 2.0.0+ so long as you blacklist that block from texture rotation.
