### ISSUE TITLE
[Forge 1.20.1] Unable to configure as config is replaced every game launch

### ISSUE THREAD

**Issue by Fokke456** [FirEmerald/DynamicVerticalSlabsAndStairs#88]
Hi!  I needed to add tags to certain blocks for compatibility with other mods, and while doing that I found that the tag manager in additional placements really does not like that. Turning it off using the config, however, I found that every time the game is launched the config works once and then gets reset. The old config gets changed into a .bak file looking like:
![image](https://github.com/user-attachments/assets/c143b111-3fff-47b7-b7d2-7bf171563f75)
In my logs I also get the following warning message:
`[14Aug2024 22:00:55.946] [Thread-3/WARN] [net.minecraftforge.fml.config.ConfigFileTypeHandler/CONFIG]: Configuration file [path]/.minecraft/config/additionalplacements-common.toml is not correct. Correcting`
According to [this](https://github.com/MinecraftForge/MinecraftForge/issues/7669) forge issue, something is going wrong on your side.

Thanks!

**Comment by FirEmerald** [comment]
should be fixed in 2.0.0+
