### ISSUE TITLE
Bug in placing stairs

### ISSUE THREAD

**Issue by tedomedo** [FirEmerald/DynamicVerticalSlabsAndStairs#89]
![slika](https://github.com/user-attachments/assets/24fd4473-6956-41df-af1e-4b74445b35e6)
![slika](https://github.com/user-attachments/assets/e1f63496-2ffa-4fae-8cbd-ff95356e8c31)
Second stairs from left side are not correct. I tried placing from every side, it was always the same. It's correct only if i remove stairs in other side corner: 
![slika](https://github.com/user-attachments/assets/17a2985c-cfec-4f14-85c6-f54f75b2d6a2)
I play minecraft forge 1.18.2.

**Comment by FirEmerald** [comment]
should have been fixed in 2.0.0.

**Comment by tedomedo** [comment]
Well, i stopped using your mod. Placing slabs horizontally on hoppers is impossible with your mod if hoppers are in the same Y as me. And placing slabs horizontally on sides of other horizontal slabs is shit too because i have to be very close to a slab to be able to see its center in order to place slab horizontally. Add option - e. g, placing something while holding a keyboard key would place it as default. 
I downloaded your mod to place carpets on ceilings. But since placing everything else is too much hard, i don't want it. Please, create another mod for placing carpets on ceiling only.

**Comment by FirEmerald** [comment]
>  Add option - e. g, placing something while holding a keyboard key would place it as default.

MF that's been an option in the mod for _months_. check your keybinds.

> Please, create another mod for placing carpets on ceiling only.

If that's all you want just disable all the other generators in the config.

**Comment by tedomedo** [comment]
I have forge in minecraft, forge isn't installed in windows and config in minecraft for your mod in grayed out. I downloaded again your mod on www.curseforge.com/minecraft/mc-mods/additional-placements/files/5898057, i got .jar. I opened .jar with 7zip. Which files and folders should i delete in order to have only carpet on ceiling function with your mod?

**Comment by FirEmerald** [comment]
No. You don't open the mod with 7zip and you don't delete any files from it. You open the config files in your config folder and use the provided configuration options.

**Comment by tedomedo** [comment]
I don't find config folder for mods. Do you know where it is for minecraft launched with TLauncher?

**Comment by tedomedo** [comment]
Oh, yes, sorry. I have additionalplacements-common.toml and additionalplacements-client.toml in \config, i opened then but i don't see what's the key for placing blocks as default. And what do i have to change to use you mod only for placing carpet on ceiling?

**Comment by FirEmerald** [comment]
>  i don't see what's the key for placing blocks as default.

that's because keybinds are always managed from the controls menu, in the in-game options menu. You don't need to mess around with the config for that unless you're trying to change the default behavior from on to off.

> what do i have to change to use you mod only for placing carpet on ceiling?

neither of the configs you listed - you're going to want additionalplacements-startup.toml, and to simple disable all other block types inside of it. All the config options are commented, and I would suggest using an app with syntax highlighting like notepad++ to edit so it's easier to read and see what you need to do.
