### ISSUE TITLE
[Fabric 1.20.1] Indium/Culling incompatibility.

### ISSUE THREAD

**Issue by tiredtires** [FirEmerald/DynamicVerticalSlabsAndStairs#90]
Whenever a mod that culls blocks is loaded, the slabs and stairs placed differently than vanilla appear invisible, and when broken, have missing texture particles. (Additionally, I played on Quilt Loader 0.53, if that has anything to do with this.)

**Comment by FirEmerald** [comment]
that sounds like the mods might be messing with how block models are grabbed from the modelshaper. which is odd, since they shouldn't need to. I've been working on some neat stuff off the repository relating to the block models though, so I won't investigate this until after it's done.

**Comment by tiredtires** [comment]
Coolio

**Comment by tiredtires** [comment]
I just checked this morning and i think i just needed to update my stuff. Sorry for opening this issue.
