### ISSUE TITLE
Unknown Mod Incompatibility Crash [2.0.0, Forge 1.20.1]

### ISSUE THREAD

**Issue by emihead** [FirEmerald/DynamicVerticalSlabsAndStairs#93]
This issue may be invalid because I haven't tested the specific other mod that AP is having issues with, but 2.0.0 is crashing my modpack. Downgrading fixes the issue completely.
If I had to guess, it may be Accessories or its Curios compat layer since that's what the logs suspect... but you never know.
I'll try testing with just those two in a different instance.

Latest.log with 2.0.0:
https://mclo.gs/fCnd3IV
Latest.log with 1.8.0:
https://mclo.gs/e29LkSK

**Comment by emihead** [comment]
Ok, I did some tests with some of the mods I saw mentioned in the crashlog and I got nothing. 
![image](https://github.com/user-attachments/assets/8de9e1c3-caa9-4ae4-ae58-abdb83fa1a7e)
Sorry for not testing more, I just have a lot of mods and not a lot of patience. Feel free to close this issue if it's invalid but maybe it's something obvious that I missed.

**Comment by Dominus-Sicarum** [comment]
Have similar problem, tested my modlist (Minecraft 1.20.1), the following mods each cause crash at startup:

[Create: Copycats+](https://www.curseforge.com/minecraft/mc-mods/copycats)
[Hexerei](https://www.curseforge.com/minecraft/mc-mods/hexerei)

Confirmed on a fresh instance with no other mods except Additional Placements and Create, since it's needed for Copycats+, installed.

**Comment by FirEmerald** [comment]
these issues are unrelated

**Comment by QianFuv** [comment]
1.19.2 forge
crash on my own modpack

**Comment by FirEmerald** [comment]
> 1.19.2 forge crash on my own modpack

1. hijacking another person's issue
2. not providing any useful information

wanna go for strike number 3?

**Comment by emihead** [comment]
Seems fixed in 2.0.1, no more crashing. Thanks!

**Comment by FirEmerald** [comment]
WTF the fix wasn't even related to this issue, or to rendering in general. All I did was change the location of the hook to dynamically create block variants.

**Comment by emihead** [comment]
I'm not even surprised lol, Minecraft is such an enigma sometimes

**Comment by emihead** [comment]
After checking things out ingame I realized the rendering is definitely a bit buggy in my pack, with sideways stairs kinda just... not working? My best guess is that it's just a side effect of this not being an intended fix, with the underlying problem still existing but causing rendering problems rather than crashing. 
![image](https://github.com/user-attachments/assets/e374a581-257b-490a-8445-cc3607823767)
Considering the game at least runs, though, I'm honestly not too pressed about it since I can just turn on the old logic for stairs anyway.

**Comment by QianFuv** [comment]
> > 1.19.2 forge crash on my own modpack
> 
> 1. hijacking another person's issue
> 2. not providing any useful information
> 
> wanna go for strike number 3?

To be honest this issue happened so suddenly, I just wanted to quickly let the developers know that this issue also happens on 1.19.2forge, I have 600+ mods in my pack and I can't find the minimum test set by dichotomizing in a short time.

**Comment by FirEmerald** [comment]
> > > 1.19.2 forge crash on my own modpack
> > 
> > 
> > 
> > 1. hijacking another person's issue
> > 2. not providing any useful information
> > 
> > wanna go for strike number 3?
> 
> To be honest this issue happened so suddenly, I just wanted to quickly let the developers know that this issue also happens on 1.19.2forge, I have 600+ mods in my pack and I can't find the minimum test set by dichotomizing in a short time.

that's not an excuse for not providing a crashlog, and then posting on someone else's issue topic that might not even be the same issue. Not all crashes are the same.

**Comment by FirEmerald** [comment]
> After checking things out ingame I realized the rendering is definitely a bit buggy in my pack, with sideways stairs kinda just... not working? My best guess is that it's just a side effect of this not being an intended fix, with the underlying problem still existing but causing rendering problems rather than crashing. ![image](https://private-user-images.githubusercontent.com/84187055/381778613-e374a581-257b-490a-8445-cc3607823767.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNDgyODcsIm5iZiI6MTczMDM0Nzk4NywicGF0aCI6Ii84NDE4NzA1NS8zODE3Nzg2MTMtZTM3NGE1ODEtMjU3Yi00OTBhLTg0NDUtY2MzNjA3ODIzNzY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDA0MTMwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2NGUyYjVmMThhY2JkY2MzZGQzZmYwODdiNDkxM2JmNzNiMjdjYTY0ZTdkYTMxODIxMDcwZTZlMjk0ZmU0MjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mtJ78Lvgc1s-H4Ee7fsSimhLfoiQclPUd_Op1os7l0c) Considering the game at least runs, though, I'm honestly not too pressed about it since I can just turn on the old logic for stairs anyway.

that's made even more strange by the fact that I specifically added a command that generates a structure that shows every single possible blockstate a stair can have, to ensure the models and collision were all correct, which I then proceeded to check across EVERY SINGLE VERSION of the mod (13 of them!) to ensure it was correct.
