### ISSUE TITLE
Slabs do not respect orientation when placed with builder's wand from Better Builder's wand.

### ISSUE THREAD

**Issue by Wileybot2004** [FirEmerald/DynamicVerticalSlabsAndStairs#97]
Game version: 1.20.1
Loader: Forge 
Video attached shows what happens when i attempt to place slabs using a builder's wand.
https://youtu.be/_L_a617oQNc

**Comment by Wileybot2004** [comment]
It appears it's not effected by all things that place multiple blocks at once, Direwolf20's Building Gadgets place normally and respect the additional placement ordination of the block so it's probably something with how Better Builder's wand does it.

**Comment by Wileybot2004** [comment]
I can now also confirm this effects forge 1.19.2 aswell

**Comment by FirEmerald** [comment]
My best guess is the wand is calling placement based on where the player is looking, which triggers the block's placement logic. I can't really do anything about this, you'll just need to try to right-click the wand where the block would normally place to get the orientation you want.
