### ISSUE TITLE
Oh the biomes weve gone compat

### ISSUE THREAD

**Issue by Poke5555** [FirEmerald/DynamicVerticalSlabsAndStairs#98]
I have both mods installed but the stairs and slabs and stuff from obwg dont seem to work? ive tried adding them to the config but the config reset everytime i modify it

Neoforge-21.1.73
additionalplacements-NeoForge-1.21-2.0.8
Oh-The-Biomes-Weve-Gone-NeoForge-2.2.2

**Comment by Poke5555** [comment]
it also seems to not work with macaws? am i just doing something wrong or?

**Comment by FirEmerald** [comment]
If the config is resetting it means you didn't edit it correctly, and it ended up having errors that made it un-parsable.
If a mod's blocks don't work, it means that they aren't using the vanilla base classes, and adding them to the config won't change anything.
