### ISSUE TITLE
Error when trying to connect to server

### ISSUE THREAD

**Issue by JaceTheGrayOne** [FirEmerald/DynamicVerticalSlabsAndStairs#99]
Minecraft: 1.21
Fabric: 0.16.9
Fabric API: 0.102.0+1.21
Mod: 2.0.8

Error:
`Internal Exception: io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:custom_payload' (additionalplacements:check_data_client)`

Normally I'd guess this is a version mismatch between the client and host but it's my server and I copied the mods folder from my server to the client PC I'm using to test it so I know it's not that.

My guess would be it's some dependency within the Fabric API but as far as I know 0.102.0 is the last Fabric API release for 1.21-

I also have Packet Fixer installed but as I understand it the only thing it really does is increase the byte limit of some state update packets, NBT tag packets, and chunk data payload packets so I don't think it would interfere with this.

**Comment by FirEmerald** [comment]
If the game crashes, post the crashlog. If it does not, post the game output log. Just posting the error message provides no useful information for me.

**Comment by gvancamp** [comment]
[latest-client.log](https://github.com/user-attachments/files/17691992/latest-client.log)
[latest-server.log](https://github.com/user-attachments/files/17691993/latest-server.log)

**Comment by FirEmerald** [comment]
Fixed in:
1.18.2: 019db4e
1.19.2: 6d4abdd
1.20.1: 13739df
1.20.2: b5e40f9
1.20.4: c068f8a
1.21: 67c9035
1.21.3: 5b31ca8
